### ISSUE TITLE
SplitterDragendEvent<SplitLayout> should provide splitter position

### ISSUE THREAD

**Issue by Duncol** [vaadin/vaadin-split-layout-flow#55] opened 2019-03-14 10:10 UTC
When working with addSplitterDragendListener, there is no parameter in the event (or it's source, i.e. SplitLayout) that would provide splitter position (e.g. for user settings persistence). We can set split position, but we cannot get it, which is asymmetric and misleading.

**Comment by denis-anisimov** [comment] 2019-03-14 10:33
Duplicate of https://github.com/vaadin/vaadin-split-layout-flow/issues/50

**Closed by denis-anisimov** 2019-03-14 10:33 UTC
